### ISSUE TITLE
upnmlminr-h.vf の字幅

### ISSUE THREAD

**Issue by aminophen** [texjporg/japanese-otf-mirror#14]
https://zrbabbler.hatenablog.com/entry/2019/02/27/203738 の「upnmlminr-hを変換しようとするとアレ」をたまたま読んだのですが，

> japanese-otfパッケージのupTeX用のフォントの一つであるupnmlminr-hの中身を調べたいと思って、vf2zvpを使おうとしても、エラーが出て変換は失敗してしまう。

とあります。確かに，

```
$ jfmutil vf2zvp --uptool upnmlminr-h
jfmutil: CHARWD value mismatch: code 00B7
```

.tfmと.vfに記録された値が食い違っているのは厳密には正しくないようです。一応

> 実際の運用としては、どのDVIウェアも「.vfの方の文字幅の情報は無視する」という動作をする。なのでupnmlminr-hは「実際にはちゃんと使える」のである。

とありますが，念のため調べてみます。

**Comment by aminophen** [comment]
charwd-00b7 ブランチで修正できたようです。

**Comment by aminophen** [comment]
問題ないはずなので 726b06e を master に送りました。

**Comment by t-tk** [comment]
有難うございます。
いくつか質問・確認したいと思います。

Q1. この変更で影響が及ぶのは vf の以下の 136個で合っていますか?
```
upbrsgexpgoth{b,bn,eb,ebn,r,rn}-[hv].vf    6
upbrsgexpmgoth{r,rn}-[hv].vf               2
upbrsgexpmin{b,bn,l,ln,r,rn}-[hv].vf       6

upbrsgnmlgoth{b,bn,eb,ebn,r,rn}-[hv].vf    6
upbrsgnmlmgoth{r,rn}-[hv].vf               2
upbrsgnmlmin{b,bn,l,ln,r,rn}-[hv].vf       6

upexpgoth{b,bn,eb,ebn,r,rn}-[hv].vf        6
upexpmgoth{r,rn}-[hv].vf                   2
upexpmin{b,bn,l,ln,r,rn}-[hv].vf           6

upnmlgoth{b,bn,eb,ebn,r,rn}-[hv].vf        6
upnmlmgoth{r,rn}-[hv].vf                   2
upnmlmin{b,bn,l,ln,r,rn}-[hv].vf           6

upphirakaku{w3,w6}-[hv].vf                 2
upphiramaruw4-[hv].vf                      1
upphiramin{w3,w6}-[hv].vf                  2

uprubygoth{b,eb,r}-[hv].vf                 3
uprubymgothr-[hv].vf                       1
uprubymin{b,l,r}-[hv].vf                   3
```

Q2: `*-v.vf` では変更があまり意味がない結果になるように思いますが、 「もともと意味が無いので特に気にしない」という認識でよいでしょうか?

japanese-otf-uptexの中で直近に解決したいような別の問題はなさそうなので、上記の確認が出来たら新版としてリリースしようと思います。

**Comment by aminophen** [comment]
Q1. → 136個で合っています。

Q2. → 「あまり意味がない」について敢えて「-v」を言及していらっしゃるのは何故でしょう？「VFの字幅が正しくなる」以上の意味がないのは確か（ZRさんによるとそもそも無視されるらしいから）ですが，それは -h も -v も同レベルだと思います。

**Comment by t-tk** [comment]
Q1: 確認有難うございます。

Q2: Adobe-Japan1-7ではHもVも CID117 が U+00B7 に対応付けられています。
横幅は半角で縦幅は全角のように見えます。
-v では横倒しされず全角幅になるのが正しいような気もします。
そうすると幅0.5になってる事が無意味なのか間違っているのか、という疑問です。

**Comment by t-tk** [comment]
今まで upnmlminr-v.tfm の U+00B7 は幅0.5でした。今回の tfmとvfの文字幅を合わせる目的には合致していると認識しました。
一方、それ(幅0.5)自体が不適切という気がしてきて、そもそも適切なのは何か、サポートする意味があるのかという疑問が出てくるのでU+00B7 の縦組みはサポート対象外ということにします。

**Comment by t-tk** [comment]
japanese-otf-uptex [v0.24](https://github.com/t-tk/japanese-otf-uptex/releases/tag/v0.24) をリリースしました。
tfm, vfを含めたパッケージをCTANに投稿しました。
タグは https://github.com/texjporg/japanese-otf-mirror/releases/tag/2019-09-07 です。

@norbusan 様、
japanese-otf-uptex-nonfree https://github.com/texjporg/japanese-otf-mirror/releases/download/2019-09-07/japanese-otf-uptex-nonfree-20190907.0.tar.gz を TLContrib にインストールしていただけますか?

**Comment by norbusan** [comment]
@t-tk tlcontribを更新しました。

**Comment by t-tk** [comment]
@aminophen さん、 @norbusan さん、ありがとうございました。
