### ISSUE TITLE
expminr-h.vf 等での CID へのマッピングについて

### ISSUE THREAD

**Issue by h20y6m** [texjporg/japanese-otf-mirror#16]
expminr-h.vf では 0x2474～0x247E 及び 0x2577～0x257E が CID+12361～CID+12371 及び CID+12383～CID+12391 に割り当てられているようですが、0x2474→CID+12361「ゔ」以外の割り当ては間違っているように見えます。（特に 0x247C～0x247E は JIS X 0213 でも存在しないコードです。）
この領域は JIS X 0208 (?) には存在しないコードですが生成スクリプトが考慮しておらず、直前のコードから連番で割当てしまっているように見えます。

```tex
\documentclass{jarticle}

% ↓コメントアウトを外すと…
%\usepackage[expert]{otf}

% expert が使えるフォントを割り当てる
\usepackage{pxchfon}
\setminchofont{KozMinPr6N-Regular.otf}
\setgothicfont{KozGoPr6N-Medium.otf}

\begin{document}
\fbox{\char\jis"2473} % ん
\fbox{\char\jis"2474} % ゔ
\fbox{\char\jis"2475} % ゕ
\fbox{\char\jis"2476} % ゖ
\fbox{\char\jis"2477} % か゚
\fbox{\char\jis"2478} % き゚
\fbox{\char\jis"2479} % く゚
\fbox{\char\jis"247A} % け゚
\fbox{\char\jis"247B} % こ゚
\fbox{\char\jis"247C}
\fbox{\char\jis"247D}
\fbox{\char\jis"247E}

\fbox{\char\jis"2573} % ン
\fbox{\char\jis"2574} % ヴ
\fbox{\char\jis"2575} % ヵ
\fbox{\char\jis"2576} % ヶ
\fbox{\char\jis"2577} % カ゚
\fbox{\char\jis"2578} % キ゚
\fbox{\char\jis"2579} % ク゚
\fbox{\char\jis"257A} % ケ゚
\fbox{\char\jis"257B} % コ゚
\fbox{\char\jis"257C} % セ゚
\fbox{\char\jis"257D} % ツ゚
\fbox{\char\jis"257E} % ト゚
\end{document}
```

**Comment by t-tk** [comment]
ざっとソースを眺めてみたら、現状では平仮名の割り当ては↓でやっているみたいです。片仮名も同様です。4区,5区全体をCIDのtfmに振り分けているようです。

https://github.com/texjporg/japanese-otf-mirror/blob/2a280e2c040baeebb2298e2417fe558dee5ebffd/japanese-otf/mkjvf#L595-L611

それで、どういう方向がよいでしょうか。
4区,5区の区点の文字でJIS X 0208の範囲以外のものをどこに割り当てるのか。私が思いついたのは下記です。

1. JIS X 0208の範囲以外はサポート外なので動作不定→現状維持
2. expertではない本文用フォントnmlminr-h.vf等はCIDではない本文用tfmの区点にそのまま割り当てている。→ expertも同様にする

> 生成スクリプトが考慮しておらず

1の考え方ならば「仕様」でもなく「バグ」でもない「動作不定」だと思います。原作者の齋藤さんは考慮した上で判断されているのかも知れません。「不正な入力に対するエラー処理」の類は事故のリスクと実装コストの兼ね合いで判断するものでしょう。今回の場合、あえてその文字コードを `\jis` などを使って作らないと出てこないもので、通常のテキスト入力をしている一般的な使い方では事故は起こりにくいという気がします。ひょっとしたら、CP932 などの機種依存文字で簡単に入力出来たりするのか、よく知りません。

原作者の齋藤さんの判断を仰ぐ前に、検討案としてここでまとめてもよいかと思います。
案2なら、コードを書いてテストして検討案をまとめる(=実装コストを払う)ことになると思います。それ以外の案もあればお願いします。

**Comment by t-tk** [comment]
もうひとつ対応案を思いつきました。

- 和文vf の fallback https://github.com/texjporg/tex-jp-build/issues/99 を前提に該当区点の vf のエントリーを生成しない。すると対応しているdviware(現状 dvipdfmx, dvips)では本文用tfmの区点に割り当てられる。

**Comment by t-tk** [comment]
CP932, MacJapanese のShiftJISの機種依存文字を確認しました。
どちらも4区の後ろの方(\char\jis"2474以降, \char\jis"2577以降)は文字が定義されていないことを確認しました。
私としては、誤入力の可能性は低いと判断し「JIS X 0208の範囲以外はサポート外なので動作不定→現状維持」の見解です。

**Comment by h20y6m** [comment]
ありがとうございます。
おっしゃるように誤入力の可能性は低そうですし、
サポート外ということであれば現状維持で良いと思います。
