### ISSUE TITLE
typo in script/mkaltutfvf.pl

### ISSUE THREAD

**Issue by t-tk** [texjporg/japanese-otf-mirror#19]
```script/mkaltutfvf.pl```に些細なtypoと思われる部分が見つかったので修正します。

組版結果には影響しないようです。
typoの影響は vf 64個

utfgr[0-9a-f]-[hv].vf :: 32個
utfmr[0-9a-f]-[hv].vf :: 32個

**Comment by t-tk** [comment]
ここで [tag 2020-11-14 ](https://github.com/texjporg/japanese-otf-mirror/releases/tag/2020-11-14)を打ち、CTANへ投稿しました。

**Comment by t-tk** [comment]
@norbusan 様、いつもお世話になります。nonfree
https://github.com/texjporg/japanese-otf-mirror/releases/download/2020-11-14/japanese-otf-nonfree-20201114.0.tar.gz
https://github.com/texjporg/japanese-otf-mirror/releases/download/2020-11-14/japanese-otf-uptex-nonfree-20201114.0.tar.gz
をTLContrib にインストールしていただけますか?
今回 japanese-otf-nonfree の中身は変更されていないのですが、他の3個には更新があるのでバージョン番号を合わせるために用意しました。

**Comment by norbusan** [comment]
@t-tk 田中様、ご連絡をありがとうございました。お疲れさまです。
更新しました。ご確認をお願いします。
よろしくお願いします。

**Comment by t-tk** [comment]
@norbusan 様、ありがとうございました。
