### ISSUE TITLE
エンジンが不正の場合のエラーメッセージ

### ISSUE THREAD

**Issue by aminophen** [texjporg/japanese-otf-mirror#2]
texjporg/jsclasses#11 とも似た議論ですが，エンジンを間違えた場合に出るエラーメッセージが

```` tex
%#!uplatex
\documentclass{jltxdoc}
\usepackage{otf}
\begin{document}
あ
\end{document}
````

````
! LaTeX Error: KANJI Encoding scheme `JY1' unknown.
````

で分かりづらいという意見があります。jsclasses では当該 issue をきっかけに

````
! Class jsarticle Error: You are running upLaTeX.
(jsarticle)              Please use pLaTeX instead, or add 'uplatex' to
(jsarticle)              the class option list.
````

というエラーメッセージを出すようになっています。

一つの案として ZR さんから「自動判定にする」というのが出ています (dev-uplatex-opt branch) が，これでは「uplatexでコンパイルするつもりだったのにplatexでコンパイルしてしまった!!」もしくはその逆のような事故を防ぐことはできません。そこで，jsclasses と同じメッセージを取り入れるのはいかがでしょうか。

**Comment by t-tk** [comment]
jsclasses での話は知りませんでした。2016年に導入済みだったのですね。
jsclasses と同様のロジックで

* 既定では自動判定せず、エラーメッセージを現状より判りやすくする
* 明示的に `autodetect-engine` オプションを加えた場合、自動判定する

という動作なら賛成です。
手元で少々やってみたのですが、 `\PackageError`, `\PackageInfo` などの使い方が分からず挫折しました。ご協力を求めます。

**Comment by aminophen** [comment]
a0fec30 で

> - 既定では自動判定せず、エラーメッセージを現状より判りやすくする
> - 明示的に autodetect-engine オプションを加えた場合、自動判定する

にしてみました。

**Comment by t-tk** [comment]
ありがとうございました。
微妙に修整し、現状 https://github.com/texjporg/japanese-otf-mirror/commit/0a2d0605dee80b8d99ade90c0761c28ea3f3d13b のようになっています。
これで本日リリースしたいと思います。
なお、ギュメの件は今回は保留したいです。

**Comment by aminophen** [comment]
> 微妙に修正

元のままでないと，autodetect-engine がエラーを吐いてしまいます。

**Comment by t-tk** [comment]
あらまあ、誤解でした。すみません。元に戻したものをリリースします。

0.19のソースを[私のところ](http://www.t-lab.opal.ne.jp/tex/uptex.html)で公開しました。
関連のブランチとissuesは、順次片づけます。

**Comment by aminophen** [comment]
元に戻したものを既に master に入れましたので，ブランチと issue を閉じて

- japanese-otf
- japanese-otf-uptex
- uptex-fonts

の3つを，私の方で CTAN upload します。
