### ISSUE TITLE
japanese-otf vfの軽量化

### ISSUE THREAD

**Issue by t-tk** [texjporg/japanese-otf-mirror#20]
[和文vf の fallback を dviware で](https://github.com/texjporg/tex-jp-build/issues/99 ) に関連し
japanese-otf-uptex の vf は先日の v0.26 で機能追加しつつ軽量化しましたが、japanese-otf の方はそのままになっています。

directory            | 2020-02-29 |  2020-11/21
---------------------|-------------|----------------
japanese-otf/vf          | 125M | 125M
japanese-otf-uptex/vf | 87M | 21M

まだまだ巨大だなと思います。
原作と離れることになりますが、japanese-otf/vf も軽量化を目指そうかと思います。
まだ正確には見積もっていませんが、6~7割程度には出来るのでないかと考えています。
時期は TeX Live 2021 に間に合うことを目指そうかと考えています。

**Comment by aminophen** [comment]
ここに関係ないような気もしますが

``` tex
%#!uptex
\jfont\XXX=utfcgr--h\XXX 中\end
```

これを uptex で処理して得た DVI は dvipdfmx で処理できるのですが，dvips で

```
This is dvips(k) 2020.1 Copyright 2020 Radical Eye Software (www.radicaleye.com)
' TeX output 2020.11.26:2053' -> jfm-test.ps
dvips: ! Bad VF file utfcgr--h.vf: unexpected command in preamble
```

と出てしまいます。原因はよくわかっていません。

**Comment by t-tk** [comment]
ご報告ありがとうございます。
dvipsの軽量vf対応が不十分である可能性が高そうです。
おそらく↓のテスト用vf (upjf_omit.vf) でもエラーが出そうな気がします。
https://www.tug.org/svn/texlive?view=revision&revision=54979

時間が出来たら調べてみます。

**Comment by t-tk** [comment]
これならばエラーは出ませんね。
``` tex
%#!uptex
\jfont\XXX=utfjgr--h\XXX 中\end
```
``` tex
%#!uptex
\tfont\XXX=utfjgr--v\tate\XXX 中\end
```

これはエラーが出ます。
``` tex
%#!uptex
\tfont\XXX=utfcgr--v\tate\XXX 中\end
```
```
dvips -u ./hoge.map chk_dvips_004.dvi 
This is dvips(k) 2020.1 Copyright 2020 Radical Eye Software (www.radicaleye.com)
' TeX output 2020.11.27:2236' -> chk_dvips_004.ps
dvips: ! Bad VF file utfcgr--v.vf: unexpected command in preamble

```

\UTF{}用(日本語用) `utfjgr--{h,v}.vf` は半角カタカナがあってエントリーが存在するのに対し,
\UTFC{}用(簡体中国語用) `utfcgr--{h,v}.vf` はエントリーが存在せず、全ての文字がfallback対象になっている点が異なります。
dvipsでそういう場合にエラーを出さないようにするだけでよいような気がします。

**Comment by t-tk** [comment]
これでいかがでしょうか。
https://github.com/texjporg/tex-jp-build/commit/70856308d60d9b17f7cf126e32e5019127220449

**Comment by t-tk** [comment]
directory            | 2020-02-29 |  2020-11/21 | https://github.com/texjporg/japanese-otf-mirror/commit/365680b63723d0123491b8927f740220ae43f0bb
---------------------|-------------|----------------|-------------
japanese-otf/vf          | 125M | 125M | 108M
japanese-otf-uptex/vf | 87M | 21M | 21M

japanese-otf の方は japanese-otf-uptex に比べて1フォント当たりの文字数が少ないのと
subfontを使っている部分( `\CID{}`, \UTF{}` などのための vf )がかなり大きいため
本文用vfの一部にvf fallback を使っても思ったより小さくならないという結果になりました。
思ったより効果が小さいため一般向け配布への本件の採用は見送ろうと思います。

subfontの部分で使用されるはずがない文字コードをvfから削除するとか、本文用vfのfallback利用をさらに進めるとかをすればもっとファイルサイズを減らすことが出来ますが、原作を尊重してそのままにしています。

**Comment by t-tk** [comment]
directory            | 2020-02-29 |  2020-11/21 | https://github.com/texjporg/japanese-otf-mirror/commit/365680b63723d0123491b8927f740220ae43f0bb |  https://github.com/texjporg/japanese-otf-mirror/commit/a77970a7caf537aec3ef2d5c8a8e199006bdcab9
---------------------|-------------|----------------|-------------|--------------
japanese-otf/vf          | 125M | 125M | 108M | 65M
japanese-otf-uptex/vf | 87M | 21M | 21M | 21M

実験として「subfontの部分で使用されるはずがない文字コードをvfから削除する」をやってみました。
ぐっと小さくなりました。
この位サイズ縮小効果があるのならば、一般向け配布へ採用してもいいような気がしてきました。
subfontの今回削減した部分は機能的には何らデメリットが無く、万一異常な入力が有った場合の保険という位置付けだったのだと思います。しかし実際にはその危険も想定しづらいので削ってもいいような気がします。

**Comment by t-tk** [comment]
japanese-otf vf の軽量化は、今回の調査で効果の大きさが確認できましたが、今の時点では不採用として閉じることにします。

**Comment by t-tk** [comment]
TeX Live mailing list の方でファイルサイズの話題が出ています。japanese-otf はやはり巨大です。
ここでの検討を復活させようと思います。

https://tug.org/pipermail/tex-live/2021-May/047027.html
https://tug.org/pipermail/tex-live/2021-May/047028.html
https://tug.org/pipermail/tex-live/2021-May/047029.html
https://tug.org/pipermail/tex-live/2021-May/047030.html

リストの中にharanoajiの文字も見えます。

**Comment by t-tk** [comment]
いろいろ試しました。方針を決めたいと思います。

commit | サイズ | omitfw | 未定義区省略 | subfont不使用分省略 | サロゲート片省略 | 未定義CID省略
-------|--------|--------|--------------|---------------------|------------------|--------------
2020/11/21 | 125M | N | N | N | N | N
https://github.com/texjporg/japanese-otf-mirror/commit/365680b63723d0123491b8927f740220ae43f0bb | 108M | Y | N | N | N | N
https://github.com/texjporg/japanese-otf-mirror/commit/a77970a7caf537aec3ef2d5c8a8e199006bdcab9 | 65M  | Y | N | Y | N | N
https://github.com/texjporg/japanese-otf-mirror/commit/f78841aa3bb9576784f249c9e4bab6987ac6a801 | 61M | Y | N | Y | Y | N | N
https://github.com/texjporg/japanese-otf-mirror/commit/10e0891016ff9ea4ef8beaf7475aa32bca5985e0 | 61M | Y | N | Y | Y | N
https://github.com/texjporg/japanese-otf-mirror/commit/34face243c31cb6b77361273ac7b85c31e42fcc1 | 59M | Y | Y | Y | Y | Y 
https://github.com/texjporg/japanese-otf-mirror/commit/0881841b845756ba25a8b94fd9240da8c0706a7f | 71M | N | Y | Y | Y | Y
https://github.com/texjporg/japanese-otf-mirror/commit/a266d8b2ca3b48877602bb006d1677740aacf639 | 72M | N | Y | Y | N | Y

omitfwとは、vf fallback機能を利用して全角のvfのエントリーを省略したものです。
未定義区省略とは、JIS X 0208(第一、第二水準)で未定義の区である9~15区と85区以上のvfのエントリーを省略したものです。
subfont不使用分省略とは、`\UTF{}`, `\CID{}`等のvfで使わないエントリーを省略したものです。
サロゲート片省略とは、`\UTF{}`等のvfで上位サロゲート(U+D800～U+DBFF)と下位サロゲート(U+DC00～U+DFFF)のエントリーを省略したものです。
未定義CID省略とは、`\CID{}`等のvfで未定義のCIDのエントリーを省略したものです。
事故防止、メンテナンス性、サイズ削減効果のバランスを考え https://github.com/texjporg/japanese-otf-mirror/commit/a266d8b2ca3b48877602bb006d1677740aacf639 をTeX JP org編集版としてCTANに出そうと思います。

**Comment by t-tk** [comment]
https://github.com/texjporg/japanese-otf-mirror/commit/a266d8b2ca3b48877602bb006d1677740aacf639 と同等のものを先ほどCTANに投稿しました。
japanese-otf-uptex の方は新たにCKの本文用vfを追加しましたが、軽量vfなのでサイズはほとんど増えていません。
ここは閉じます。

directory            | 2020-02-29 |  2020-11/21 | 2022-02-17
---------------------|-------------|----------------|-------------
japanese-otf/vf          | 125M | 125M |  72M
japanese-otf-uptex/vf | 87M | 21M   |  21M
