### ISSUE TITLE
Unicode 15.0, 小書き仮名「こ」「コ」更新

### ISSUE THREAD

**Issue by t-tk** [texjporg/japanese-otf-mirror#24]
@norbusan さん
いつもありがとうございます。
japanese-otf-uptex の更新に伴い nonfree の vf も更新があります。
(CTAN投稿の後、忘れていました)

https://github.com/texjporg/japanese-otf-mirror/releases/tag/2023-02-23
の
[japanese-otf-nonfree-20230223.0.tar.gz](https://github.com/texjporg/japanese-otf-mirror/releases/download/2023-02-23/japanese-otf-nonfree-20230223.0.tar.gz)
を TLContrib にインストールしていただけるとありがたいです。

Ref.
[Unicode 15.0.0](https://github.com/texjporg/tex-jp-build/issues/141#top)
[小書き仮名「こ」「コ」](https://github.com/t-tk/japanese-otf-uptex/issues/6#top)

**Comment by norbusan** [comment]
@t-tk これはTL2023のtlcontribのためですか？TL2022のtlcontribにも入れるつもりですか？
TL2023のtlcontribは <= TL2022のtlcontrib と違いますから、教えてください。

**Comment by t-tk** [comment]
これは TL2022 でも動きます。
なので、TL2022のtlcontribにも入れていただけると有難いです。

**Comment by norbusan** [comment]
今 `current == 2022` と `2023` に入れておきました。ご確認をお願いします。
`current == 2022` はこれから2023 pretestに対応していません。
Pretestを使う方は、`current`の変わりに`2023`をいれないといけません。
TL2023がリリースされてから、current -> 2023になります。

よろしくお願いいたします。

**Comment by t-tk** [comment]
ありがとうございました。
ここは閉じます。
