### ISSUE TITLE
CTAN投稿、 TLContrib

### ISSUE THREAD

**Issue by t-tk** [texjporg/japanese-otf-mirror#27]
@norbusan さん
いつもありがとうございます。
japanese-otf-uptex の更新に伴い CTANに投稿しました。

nonfree は今回 readme の更新のみで、重要性はありませんがお願いがあります。

https://github.com/texjporg/japanese-otf-mirror/releases/tag/2023-10-09
の
[japanese-otf-nonfree-20231009.0.tar.gz](https://github.com/texjporg/japanese-otf-mirror/releases/download/2023-10-09/japanese-otf-nonfree-20231009.0.tar.gz)
を TLContrib にインストールしていただけるとありがたいです。

**Comment by norbusan** [comment]
ただいまアップしました。
ありがとうございました。
