### ISSUE TITLE
Please update  the cid jvf for Adobe GB 1-6

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [texjporg/japanese-otf-mirror#29]
Adobe GB 1-6 have been updated on 2023-04-21,  which include more 288 char for the GB18030-2022 L2 level, 

Please update the cid jvf with (cidcmr7-h.vf and cidcmr7-v.vf )

Thank you very much.

by

(CHARACTER H 493C
   (MAP
      (SETCHAR H 764C)
      )
   )

to

(CHARACTER H 4D5B
   (MAP
      (SETCHAR H 776B)
      )
   )

764C  to cid30284
776B  to cid30571

I tried to gernerate the couple of (cidcmr7-h.vf and cidcmr7-v.vf ) but faild with the error code:

>perl jfmutil.pl zvp2vf cidcmr7-v.zvp
jfmutil: VPL syntax error: bad argument: (VTITLE JVF for Adobe-GB1-5)

>perl jfmutil.pl zvp2vf cidcmr7-h.zvp
jfmutil: VPL syntax error: bad argument: (VTITLE JVF for Adobe-GB1-5)

and 

>perl jfmutil.pl zvp2vf cidcmr6-v.zvp
jfmutil: VPL syntax error: bad argument: (VTITLE JVF for Adobe-GB1-5)

Please help me.

**Comment by t-tk** [comment]
`cidcmr7-v.vf` is generated by `japanese-otf/script/mkmlcidvf.pl` and max of Adobe-GB is now 30283 (Adobe-GB1-5)
https://github.com/texjporg/japanese-otf-mirror/blob/641eb1289c9cb0b7952ea0c0d5edf4163ca29ce1/japanese-otf/script/mkmlcidvf.pl#L107

If you replace it like `s/30283/30571/`, you will get the larger one (AG1-6).

I do not have a plan to update above because `cidcmr[0-7]-v.vf` is only used with platex
and  the combination of  `cidcmr--v.vf` and uplatex have already supported Adobe-GB1-6 by using vf fallback (ref. https://github.com/texjporg/tex-jp-build/issues/99)

I hope you to understand the situation.

**Comment by Steve-Cheung-emct** [comment]
I got it, thank you for reply.

best wish


________________________________
发件人: TANAKA, Takuji ***@***.***>
发送时间: 2024年10月2日 17:03
收件人: texjporg/japanese-otf-mirror ***@***.***>
抄送: Steve-Cheung-emct ***@***.***>; Author ***@***.***>
主题: Re: [texjporg/japanese-otf-mirror] Please update the cid jvf for Adobe GB 1-6 (Issue #29)


cidcmr7-v.vf is generated by japanese-otf/script/mkmlcidvf.pl and max of Adobe-GB is now 30283 (Adobe-GB1-5)
https://github.com/texjporg/japanese-otf-mirror/blob/641eb1289c9cb0b7952ea0c0d5edf4163ca29ce1/japanese-otf/script/mkmlcidvf.pl#L107

If you replace it like s/30283/30571/, you will get the larger one (AG1-6).

I do not have a plan to update above because cidcmr[0-7]-v.vf is only used with platex
and the combination of cidcmr--v.vf and uplatex have already supported Adobe-GB1-6 by using vf fallback (ref. texjporg/tex-jp-build#99<https://github.com/texjporg/tex-jp-build/issues/99>)

I hope you to understand the situation.

―

**Comment by Steve-Cheung-emct** [comment]
I replace it by s/30283/30571/ and regernerate cidcmr7-h.vf cidcmr7-v.vf cidcgr7-h.vf cidgr7-v.vf and cover it by thoes new-type.


Then I try to call "\CIDC{30571}" and get the corrent Kanji (U+2CE93) not the bad one.

Thank you very much.





________________________________
发件人: TANAKA, Takuji ***@***.***>
发送时间: 2024年10月2日 17:03
收件人: texjporg/japanese-otf-mirror ***@***.***>
抄送: Steve-Cheung-emct ***@***.***>; Author ***@***.***>
主题: Re: [texjporg/japanese-otf-mirror] Please update the cid jvf for Adobe GB 1-6 (Issue #29)


cidcmr7-v.vf is generated by japanese-otf/script/mkmlcidvf.pl and max of Adobe-GB is now 30283 (Adobe-GB1-5)
https://github.com/texjporg/japanese-otf-mirror/blob/641eb1289c9cb0b7952ea0c0d5edf4163ca29ce1/japanese-otf/script/mkmlcidvf.pl#L107

If you replace it like s/30283/30571/, you will get the larger one (AG1-6).

I do not have a plan to update above because cidcmr[0-7]-v.vf is only used with platex
and the combination of cidcmr--v.vf and uplatex have already supported Adobe-GB1-6 by using vf fallback (ref. texjporg/tex-jp-build#99<https://github.com/texjporg/tex-jp-build/issues/99>)

I hope you to understand the situation.

―
