### ISSUE TITLE
ハングル on upLaTeX

### ISSUE THREAD

**Issue by aminophen** [texjporg/japanese-otf-mirror#5]
japanese-otf/test/koreanexample.tex は，冒頭の \documentclass[papersize]{jsarticle} を

\documentclass[papersize,autodetect-engine]{jsarticle}

に変えると「pLaTeX / upLaTeX 両方で通るべきソース」だと思いますが，upLaTeX で作った DVI を dvipdfmx で処理しようとすると

````
char=0xc740(51008)
Tried to set a nonexistent character in a virtual font
````

のように大量の警告が出て，韓国語の文字が消えます。pLaTeX は正常です。

**Comment by aminophen** [comment]
よく見ると，pLaTeX ではハングルが欧文扱いなので inputenc を通って出てくる一方，upLaTeX では CJK トークン扱いされているだけでしょうか。韓国語ではなく日本語の VF が割り当てられているため，消えるのは仕様通りな気がしてきました。

**Comment by t-tk** [comment]
試してみました。
この現象は、ハングルを生のUTF-8で書いているところを
pLaTeX の場合には otf-hangul.dfu 経由で \UTFK{} に変換して出力しているのに対し、
upLaTeX の場合には dfu に渡る前にCJKトークン化され本文用の文字として処理しようとするためです。

https://github.com/texjporg/uptex-base/blob/master/samples/cjk_babel.tex と似たような方法で該当するブロックにおいて本文用フォントとして韓国語のフォントを指定すれば、ハングルが出ます。
あるいは、ZRさんの PXパッケージを使っても出来るはずです。

\UTFM{}のようなことを upTeX の本文用フォントで実現しようとするならば、CJKを包含して振り分けるようなVFを作るのが良いかもしれません。
その場合、マクロ・パッケージ作者さんが使えるような道具はすでに揃っていると思うので、私が頑張らなくてもよいかなと思います。

**Comment by aminophen** [comment]
ありがとうございます。こちらは標準でサポートすることではないと思うので閉じます。
