### ISSUE TITLE
[jotf-uptex] 二重感嘆符、hirapropの半角カタカナ

### ISSUE THREAD

**Issue by t-tk** [texjporg/japanese-otf-mirror#6]
https://github.com/texjporg/platex/issues/73 で話題に出ていた件、
japanese-otf-uptex の縦組みで、[区切り約物 cl-04](https://www.w3.org/TR/jlreq/ja/#cl-04) を同列に扱おうとするならば、以下の4グリフもtype 6 にすべきのようです。

CIDの対応はUniJIS-UTF16-{H,V}のもの
U+203C ‼ CID:12111 全角
U+2047 ⁇ CID:16278 全角
U+2048 ⁈ CID:16279 全角
U+2049 ⁉ CID:12112 全角

また、未実装だった「japanese-otf-uptex & hiraprop & 横組み & 半角カタカナ」の対応も進めています。
こちら https://github.com/texjporg/japanese-otf-mirror/tree/exclamation で修正・テストしています。

**Comment by t-tk** [comment]
手元でtfm, vfの再生成、テスト、ドキュメントの更新まで進みました。予定通りに動いているようです。
現状は、https://github.com/texjporg/japanese-otf-mirror/commit/99f6769f86d05fc888fbd1d8a896f0fcdfeeab09 です。

何もなければ5/13の日曜にリリース予定です。
何かあればご指摘歓迎します。

**Comment by t-tk** [comment]
[私のサイト](http://www.t-lab.opal.ne.jp/tex/uptex.html)でソースコードをリリース、
tfm, vfを含めたパッケージをCTANに投稿しました。
タグは https://github.com/texjporg/japanese-otf-mirror/releases/tag/2018-05-13 です。

@norbusan 様、
japanese-otf-uptex-nonfree https://github.com/texjporg/japanese-otf-mirror/releases/download/2018-05-13/japanese-otf-uptex-nonfree-20180513.0.tar.gz を TLContrib にインストールしていただけますか?

**Comment by norbusan** [comment]
了解です。今晩します。

**Comment by norbusan** [comment]
アップデートしました。

**Comment by t-tk** [comment]
ご協力ありがとうございました。
