### ISSUE TITLE
Some typos

### ISSUE THREAD

**Issue by Man-Ting-Fang** [texjporg/japanese-otf-mirror#8]
`redeffont.sty` line 150: `\Hugepart...` -> `\Huge\part...`

`paren0.tex` lines 9 *and* 31: `{300A}{300B}` -> `{300C}{300D}`

`00otf-uptex.txt` line 31: `CNS` -> `GB` *and* line 32: `GB` -> `CNS`

**Comment by t-tk** [comment]
Thank @Man-Ting-Fang for the kind report!
